language: php
sudo: false
php:
  - 7.0
notifications:
  email: false
before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer install
  - rm --force /tmp/proximate.log
script:
  - vendor/bin/phpunit
after_script:
  - echo "Proxy log"
  - cat /tmp/proximate.log
